site_name: K-Cards
site_description: A K-Cards web application to automatically moderate Q&A sessions.
site_author: K-Cards
repo_url: https://github.com/kcards/kcards

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
