site_name: kcards
site_description: A KCards web service for moderating Q&A Sessions easily
site_author: Kcards
repo_url: https://github.com/kcards/kcards

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
